services:
  frontend:
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm install && npm run dev:backend"
